---
- name: Ensure audit log file ownership and permissions are compliant
  hosts: all
  become: yes
  tasks:

    - name: Ensure audit log files are owned by root
      shell: |
        [ -f /etc/audit/auditd.conf ] && \
        find "$(dirname $(awk -F "=" '/^s*log_file/ {print $2}' /etc/audit/auditd.conf | xargs))" \
        -type f ! -user root -exec chown root {} +
      changed_when: false

    - name: Ensure audit log files are group-owned by adm
      shell: |
        [ -f /etc/audit/auditd.conf ] && \
        find "$(dirname $(awk -F "=" '/^s*log_file/ {print $2}' /etc/audit/auditd.conf | xargs))" \
        -type f ! -group adm -exec chgrp adm {} +
      changed_when: false

    - name: Ensure /var/log/audit is group-owned by adm
      file:
        path: /var/log/audit
        group: adm
        recurse: yes

    - name: Set log_group = adm in auditd.conf
      lineinfile:
        path: /etc/audit/auditd.conf
        regexp: '^(\s*#\s*)?log_group\s*='
        line: 'log_group = adm'
        create: yes
        backup: yes

    - name: Reload auditd rules (instead of restart)
      command: augenrules --load
