---
- name: Harden audit log and config file permissions
  hosts: all
  become: yes
  vars:
    audit_group: adm
    audit_conf_file: /etc/audit/auditd.conf
    audit_log_dir: /var/log/audit
    audit_rule_dir: /etc/audit
    auditd_unit_file: /usr/lib/systemd/system/auditd.service

  tasks:

    - name: Ensure adm group exists
      group:
        name: "{{ audit_group }}"
        state: present

    - name: Set log_group in auditd.conf to adm
      lineinfile:
        path: "{{ audit_conf_file }}"
        regexp: '^log_group\s*='
        line: "log_group = {{ audit_group }}"
        create: yes
        backup: yes

    - name: Get list of audit log files
      find:
        paths: "{{ audit_log_dir }}"
        file_type: file
      register: audit_logs

    - name: Get stat info for audit log files
      stat:
        path: "{{ item.path }}"
      loop: "{{ audit_logs.files }}"
      register: audit_log_stats

    - name: Fix group ownership for audit log files not owned by root or adm
      file:
        path: "{{ item.stat.path }}"
        group: "{{ audit_group }}"
      loop: "{{ audit_log_stats.results }}"
      when: item.stat.grp is defined and item.stat.grp not in ['root', audit_group]

    - name: Restrict audit configuration file permissions to 0640 or more restrictive
      find:
        paths: "{{ audit_rule_dir }}"
        patterns: '*.conf,*.rules'
        file_type: file
        recurse: yes
      register: audit_conf_files

    - name: Set permissions on audit configuration files
      file:
        path: "{{ item.path }}"
        mode: "0640"
      loop: "{{ audit_conf_files.files }}"

    - name: Check if auditd can be restarted manually
      command: systemctl cat auditd
      register: auditd_status
      changed_when: false
      failed_when: false

    - name: Restart auditd if possible
      service:
        name: auditd
        state: restarted
      when: "'RefuseManualStart=yes' not in auditd_status.stdout"

    - name: Load audit rules using augenrules
      command: augenrules --load
      register: augenrules_output
      failed_when: "'error' in augenrules_output.stderr.lower() or 'was logfile' in augenrules_output.stderr"

    - name: Debug augenrules output
      debug:
        var: augenrules_output
