---
- name: Ensure time-change audit rules are applied
  hosts: all
  become: true
  tasks:
    - name: Ensure time-change audit rules file exists
      copy:
        dest: /etc/audit/rules.d/50-time-change.rules
        content: |
          -a always,exit -F arch=b64 -S adjtimex,settimeofday,clock_settime -k time-change
          -a always,exit -F arch=b32 -S adjtimex,settimeofday,clock_settime -k time-change
          -w /etc/localtime -p wa -k time-change
        mode: '0644'
        owner: root
        group: root

    - name: Reload audit rules
      command: augenrules --load
      ignore_errors: yes

    - name: Check if time-change rules are applied
      command: auditctl -l
      register: audit_rules
      failed_when: "'time-change' not in audit_rules.stdout"

    - name: Fail if time-change rules are not applied
      fail:
        msg: "Time-change audit rules are not applied correctly."
      when: "'time-change' not in audit_rules.stdout"

