---
- name: Ensure time-change audit rules are applied
  hosts: all
  become: true

  tasks:

    - name: Backup /etc/audit/rules.d/50-time-change.rules if it exists
      copy:
        src: /etc/audit/rules.d/50-time-change.rules
        dest: /etc/audit/rules.d/50-time-change.rules.bak
        remote_src: true
      ignore_errors: true

    - name: Backup /etc/audit/audit.rules if it exists
      copy:
        src: /etc/audit/audit.rules
        dest: /etc/audit/audit.rules.bak
        remote_src: true
      ignore_errors: true

    - name: Remove duplicate time-change rules from audit.rules (if any)
      lineinfile:
        path: /etc/audit/audit.rules
        state: absent
        regexp: '.*(adjtimex|settimeofday|clock_settime|-w /etc/localtime).*'
      ignore_errors: true
      notify: Reload audit rules

    - name: Ensure correct time-change rules file exists
      copy:
        dest: /etc/audit/rules.d/50-time-change.rules
        content: |
          -a always,exit -F arch=b64 -S adjtimex,settimeofday,clock_settime -k time-change
          -a always,exit -F arch=b32 -S adjtimex,settimeofday,clock_settime -k time-change
          -w /etc/localtime -p wa -k time-change
        owner: root
        group: root
        mode: '0644'
      notify: Reload audit rules

    - name: Wait briefly for rules to apply
      pause:
        seconds: 2

    - name: Get current audit rules
      command: auditctl -l
      register: auditctl_output
      changed_when: false

    - name: Validate required time-change audit rules
      vars:
        required_rules:
          - "^-a always,exit -F arch=b64 -S adjtimex .* -k time-change"
          - "^-a always,exit -F arch=b64 -S settimeofday .* -k time-change"
          - "^-a always,exit -F arch=b64 -S clock_settime .* -k time-change"
          - "^-a always,exit -F arch=b32 -S adjtimex .* -k time-change"
          - "^-a always,exit -F arch=b32 -S settimeofday .* -k time-change"
          - "^-a always,exit -F arch=b32 -S clock_settime .* -k time-change"
          - "^-w /etc/localtime -p wa -k time-change"
      fail:
        msg: "One or more required audit rules are missing."
      when: auditctl_output.stdout_lines | reject('search', item) | list | length > 0
      loop: "{{ required_rules }}"

    - name: Show audit rules (debug)
      debug:
        var: auditctl_output.stdout_lines

  handlers:
    - name: Reload audit rules
      command: augenrules --load
