---
- name: Ensure time-change audit rules are applied
  hosts: all
  become: true

  tasks:
    - name: Backup existing /etc/audit/rules.d/50-time-change.rules if it exists
      copy:
        src: /etc/audit/rules.d/50-time-change.rules
        dest: /etc/audit/rules.d/50-time-change.rules.bak
        remote_src: true
      ignore_errors: true

    - name: Backup /etc/audit/audit.rules (legacy rule file)
      copy:
        src: /etc/audit/audit.rules
        dest: /etc/audit/audit.rules.bak
        remote_src: true
      ignore_errors: true

    - name: Remove conflicting time-change rules from audit.rules (if any)
      lineinfile:
        path: /etc/audit/audit.rules
        state: absent
        regexp: '.*(adjtimex|settimeofday|clock_settime|-w /etc/localtime).*'
      notify: Reload audit rules

    - name: Ensure correct time-change rules in rules.d
      copy:
        dest: /etc/audit/rules.d/50-time-change.rules
        content: |
          -a always,exit -F arch=b64 -S adjtimex,settimeofday,clock_settime -k time-change
          -a always,exit -F arch=b32 -S adjtimex,settimeofday,clock_settime -k time-change
          -w /etc/localtime -p wa -k time-change
        owner: root
        group: root
        mode: '0644'
      notify: Reload audit rules

    - name: Pause to allow audit rules to apply
      pause:
        seconds: 2

    - name: Get current audit rules
      command: auditctl -l
      register: auditctl_output
      changed_when: false

    - name: Fail if adjtimex rule is missing
      fail:
        msg: "Missing audit rule for adjtimex (b64)"
      when: auditctl_output.stdout is not search('adjtimex.*-k time-change')

    - name: Fail if settimeofday rule is missing
      fail:
        msg: "Missing audit rule for settimeofday (b64)"
      when: auditctl_output.stdout is not search('settimeofday.*-k time-change')

    - name: Fail if clock_settime rule is missing
      fail:
        msg: "Missing audit rule for clock_settime (b64)"
      when: auditctl_output.stdout is not search('clock_settime.*-k time-change')

    - name: Fail if /etc/localtime watch rule is missing
      fail:
        msg: "Missing audit rule for /etc/localtime"
      when: auditctl_output.stdout is not search('-w /etc/localtime -p wa -k time-change')

    - name: Show current audit rules (for debugging)
      debug:
        var: auditctl_output.stdout_lines

  handlers:
    - name: Reload audit rules
      command: augenrules --load
