---
- name: Ensure time-change audit rules are applied
  hosts: all
  become: true
  tasks:
    - name: Ensure time-change audit rules file exists
      copy:
        dest: /etc/audit/rules.d/50-time-change.rules
        content: |
          -a always,exit -F arch=b64 -S adjtimex,settimeofday,clock_settime -k time-change
          -a always,exit -F arch=b32 -S adjtimex,settimeofday,clock_settime -k time-change
          -w /etc/localtime -p wa -k time-change
        mode: '0644'
        owner: root
        group: root

    - name: Reload audit rules
      command: augenrules --load
      ignore_errors: yes

    - name: Wait for a short time to ensure rules are loaded
      pause:
        seconds: 2

    - name: Check if time-change rules are applied
      command: auditctl -l
      register: audit_rules
      failed_when: "'time-change' not in audit_rules.stdout"

    - name: Fail if time-change rules are not applied
      fail:
        msg: "Time-change audit rules are not applied correctly."
      when: "'time-change' not in audit_rules.stdout"

    - name: Validate time-change rules for adjtimex (b64)
      command: auditctl -l | grep -E "adjtimex.*time-change"
      register: adjtimex_rule
      failed_when: adjtimex_rule.stdout == ""
      ignore_errors: yes

    - name: Validate time-change rules for settimeofday (b64)
      command: auditctl -l | grep -E "settimeofday.*time-change"
      register: settimeofday_rule
      failed_when: settimeofday_rule.stdout == ""
      ignore_errors: yes

    - name: Validate time-change rules for clock_settime (b64)
      command: auditctl -l | grep -E "clock_settime.*time-change"
      register: clock_settime_rule
      failed_when: clock_settime_rule.stdout == ""
      ignore_errors: yes

    - name: Fail if any of the time-change rules are missing
      fail:
        msg: "One or more time-change audit rules are missing."
      when: 
        - adjtimex_rule.stdout == ""
        - settimeofday_rule.stdout == ""
        - clock_settime_rule.stdout == ""
