---
- name: Ensure time-change audit rules are applied correctly
  hosts: all
  become: true

  tasks:
    - name: Backup current audit rule files
      copy:
        src: "{{ item }}"
        dest: "{{ item }}.bak"
        remote_src: true
      loop:
        - /etc/audit/rules.d/50-time-change.rules
        - /etc/audit/audit.rules
      ignore_errors: true

    - name: Remove legacy /etc/audit/audit.rules content to avoid augenrules errors
      copy:
        dest: /etc/audit/audit.rules
        content: ""
        owner: root
        group: root
        mode: '0640'

    - name: Create time-change audit rule file
      copy:
        dest: /etc/audit/rules.d/50-time-change.rules
        content: |
          -a always,exit -F arch=b64 -S adjtimex,settimeofday,clock_settime -k time-change
          -a always,exit -F arch=b32 -S adjtimex,settimeofday,clock_settime -k time-change
          -w /etc/localtime -p wa -k time-change
        owner: root
        group: root
        mode: '0644'

    - name: Flush all existing audit rules
      command: auditctl -D

    - name: Reload audit rules from rules.d using augenrules
      command: augenrules --load

    - name: Pause briefly to let audit rules apply
      pause:
        seconds: 2

    - name: Get current audit rules
      command: auditctl -l
      register: auditctl_output
      changed_when: false

    - name: Validate required time-change audit rules
      vars:
        required_rules:
          - "^-a always,exit -F arch=b64 -S adjtimex .* -k time-change"
          - "^-a always,exit -F arch=b64 -S settimeofday .* -k time-change"
          - "^-a always,exit -F arch=b64 -S clock_settime .* -k time-change"
          - "^-a always,exit -F arch=b32 -S adjtimex .* -k time-change"
          - "^-a always,exit -F arch=b32 -S settimeofday .* -k time-change"
          - "^-a always,exit -F arch=b32 -S clock_settime .* -k time-change"
          - "^-w /etc/localtime -p wa -k time-change"
      fail:
        msg: "One or more required audit rules are missing."
      when: auditctl_output.stdout_lines | reject('search', item) | list | length > 0
      loop: "{{ required_rules }}"

    - name: Debug current audit rules
      debug:
        var: auditctl_output.stdout_lines
