---
- name: Ensure file deletion events are collected
  hosts: all
  become: yes
  tasks:
    - name: Create audit rule to monitor file deletion events
      copy:
        dest: "/etc/audit/rules.d/50-delete.rules"
        content: |
          # Monitor file deletion and renaming by users
          UID_MIN=$(awk '/^UID_MIN/{print $2}' /etc/login.defs)
          if [ -n "$UID_MIN" ]; then
            echo "-a always,exit -F arch=b64 -S rename,unlink,unlinkat,renameat -F auid>=\$UID_MIN -F auid!=unset -F key=delete" >> /etc/audit/rules.d/50-delete.rules
            echo "-a always,exit -F arch=b32 -S rename,unlink,unlinkat,renameat -F auid>=\$UID_MIN -F auid!=unset -F key=delete" >> /etc/audit/rules.d/50-delete.rules
          else
            echo "ERROR: UID_MIN variable is unset" >&2
          fi
      when: ansible_facts['distribution'] != 'RedHat'

    - name: Ensure audit rules are loaded
      command: augenrules --load
      register: augenrules_output
      notify:
        - Check audit rules

    - name: Wait for a moment before checking if audit rules are loaded
      pause:
        seconds: 5

    - name: Ensure audit service is running
      service:
        name: auditd
        state: started
        enabled: yes

  handlers:
    - name: Check audit rules
      command: auditctl -l
      register: auditctl_output

    - name: Print the audit rules output
      debug:
        msg: "{{ auditctl_output.stdout }}"
