---
- name: CIS 5.2.3.10 - Audit mount syscall (b32 and b64)
  hosts: all
  become: yes
  vars:
    audit_mount_rules: "/etc/audit/rules.d/50-mounts.rules"

  tasks:
    - name: Get UID_MIN from login.defs
      command: awk '/^\s*UID_MIN/ { print $2 }' /etc/login.defs
      register: uid_min_result
      changed_when: false

    - name: Ensure mount audit rules exist
      template:
        src: "50-mounts.rules.j2"
        dest: "{{ audit_mount_rules }}"
        owner: root
        group: root
        mode: '0640'

    - name: Load audit rules
      command: augenrules --load
      register: load_result
      failed_when: load_result.rc != 0 and "No rules" in load_result.stdout
      changed_when: false

    - name: Check if reboot is required due to auditctl status = 2
      shell: |
        if [[ $(auditctl -s | grep enabled) =~ "2" ]]; then
          echo "Reboot required to load rules"
        fi
      register: reboot_required_check
      changed_when: false
