---
- name: Ensure changes to system administration scope (sudoers) are collected (CIS 5.2.3.1)
  hosts: all
  become: yes
  tasks:

    - name: Ensure audit rule for /etc/sudoers exists
      lineinfile:
        path: /etc/audit/rules.d/50-scope.rules
        line: "-w /etc/sudoers -p wa -k scope"
        create: yes
        mode: '0640'
        state: present
      notify: Reload audit rules

    - name: Ensure audit rule for /etc/sudoers.d exists
      lineinfile:
        path: /etc/audit/rules.d/50-scope.rules
        line: "-w /etc/sudoers.d -p wa -k scope"
        create: yes
        mode: '0640'
        state: present
      notify: Reload audit rules

    - name: Check if audit is in immutable mode (enabled 2)
      command: auditctl -s
      register: auditctl_status
      changed_when: false

    - name: Warn if audit is in immutable mode and reboot may be required
      debug:
        msg: "⚠️ auditd is in immutable mode (enabled 2). A reboot is required to load new rules."
      when: "'enabled 2' in auditctl_status.stdout"

  handlers:

    - name: Reload audit rules
      command: augenrules --load
