---
- name: Configure and load audit rules for monitoring sudo log
  hosts: all
  become: yes
  tasks:

    # Step 1: Check and create sudo log monitoring rule
    - name: Create sudo log monitoring rule file
      copy:
        dest: /etc/audit/rules.d/50-sudo.rules
        content: |
          # Ensure sudo log file is monitored for modifications
          SUDO_LOG_FILE=$(grep -r logfile /etc/sudoers* | sed -e 's/.*logfile=//;s/,? .*//' -e 's/""//g')
          [ -n "${SUDO_LOG_FILE}" ] && echo "-w ${SUDO_LOG_FILE} -p wa -k sudo_log_file" >> /etc/audit/rules.d/50-sudo.rules || echo "ERROR: Variable 'SUDO_LOG_FILE' is unset."

    # Step 2: Verify the existence of sudo log file in sudoers configuration
    - name: Verify sudo log file exists in sudoers configuration
      shell: |
        SUDO_LOG_FILE=$(grep -r logfile /etc/sudoers* | sed -e 's/.*logfile=//;s/,? .*//' -e 's/""//g')
        echo "SUDO_LOG_FILE: ${SUDO_LOG_FILE}"
      register: sudo_log_file_check
      failed_when: sudo_log_file_check.stdout == ""

    # Step 3: Check if the sudo log file monitoring rule is present in current rules
    - name: Check if sudo log file monitoring rule exists in auditctl
      shell: |
        SUDO_LOG_FILE_ESCAPED=$(grep -r logfile /etc/sudoers* | sed -e 's/.*logfile=//;s/,? .*//' -e 's/""//g' -e 's|/|\\/|g')
        auditctl -l | grep -E "^ *-w.*${SUDO_LOG_FILE_ESCAPED}.*-p.*wa" || echo "FAIL"
      register: auditctl_check
      failed_when: "'FAIL' in auditctl_check.stdout"

    # Step 4: Merge and load the audit rules
    - name: Merge and load the audit rules
      command: augenrules --load
      register: augenrules_load
      failed_when: augenrules_load.rc != 0
      ignore_errors: yes

    # Step 5: Check if reboot is required
    - name: Check if reboot is required to apply audit rules
      shell: |
        if [[ $(auditctl -s | grep "enabled") =~ "2" ]]; then
          echo "Reboot required to load rules"
        else
          echo "No reboot required"
        fi
      register: reboot_check

    # Step 6: Output audit rule load result and reboot requirement
    - name: Output audit rule load result
      debug:
        msg: "Audit rules loaded. Reboot check: {{ reboot_check.stdout }}"

    # Optional: Restart auditd to ensure rules are applied
    - name: Restart auditd service to apply rules
      systemd:
        name: auditd
        state: restarted
      when: reboot_check.stdout == "Reboot required to load rules"
