---
- name: Ensure audit rule for sudo log is applied
  hosts: all
  become: yes
  vars:
    sudo_log_file: /var/log/sudo.log

  handlers:
    - name: restart auditd
      service:
        name: auditd
        state: restarted

  tasks:
    - name: "Check current audit rules for sudo log"
      command: auditctl -l
      register: auditctl_output
      changed_when: false

    - name: "Ensure audit rule is present for sudo log"
      lineinfile:
        path: /etc/audit/rules.d/50-sudo.rules
        line: "-w {{ sudo_log_file }} -p wa -k sudo_log"
        create: yes
        state: present
        owner: root
        group: root
        mode: '0640'

    - name: "Reload audit rules"
      command: augenrules --load
      notify: restart auditd
      changed_when: true

    - name: "Re-check audit rules after reload"
      command: auditctl -l
      register: auditctl_output
      changed_when: false

    - name: "Fail if the audit rule for sudo log file is not applied"
      fail:
        msg: "Audit rule for sudo log file is not properly applied"
      when: auditctl_output.stdout is not search("-w " ~ sudo_log_file ~ ".*-p.*wa")
