---
- name: Ensure events that modify the sudo log file are collected
  hosts: all
  become: true

  tasks:
    - name: Check if SELinux is enforcing
      command: getenforce
      register: selinux_status
      changed_when: false
      failed_when: false

    - name: Set SELinux to permissive if enforcing
      command: setenforce 0
      when: selinux_status.stdout == "Enforcing"
      notify:
        - Revert SELinux to enforcing

    - name: Check audit system status
      command: auditctl -s
      register: audit_status
      changed_when: false

    - name: Parse audit immutable setting
      set_fact:
        audit_immutable: "{{ audit_status.stdout_lines | select('search', '^immutable') | map('split') | map('last') | first | int }}"

    - name: Disable immutable mode if set to 1
      command: auditctl -e 0
      when: audit_immutable == 1
      notify: Re-enable immutable mode

    - name: Skip if audit system is permanently immutable (mode 2)
      debug:
        msg: "Audit system is in immutable mode (2); skipping disable."
      when: audit_immutable == 2

    - name: Ensure the logfile directive is set in sudoers
      lineinfile:
        path: /etc/sudoers
        regexp: '^Defaults\s+logfile='
        line: 'Defaults logfile="/var/log/sudo.log"'
        validate: '/usr/sbin/visudo -cf %s'
      notify:
        - Reload sudoers

    - name: Get sudo log file path from sudoers
      shell: grep -rE '^Defaults\s+logfile=' /etc/sudoers* | sed -E 's/.*logfile="?([^",]+)"?.*/\1/' | head -n 1
      register: sudo_log_path
      changed_when: false

    - name: Set sudo_log_file variable
      set_fact:
        sudo_log_file: "{{ sudo_log_path.stdout | trim }}"

    - name: Escape sudo log file path for audit rule check
      set_fact:
        sudo_log_file_escaped: "{{ sudo_log_file | regex_replace('/', '\\\\/') }}"

    - name: Add audit rule for sudo log file if not present
      lineinfile:
        path: /etc/audit/rules.d/50-sudo.rules
        line: "-w {{ sudo_log_file }} -p wa -k sudo_log_file"
        create: yes
        state: present
      when: sudo_log_file != ""

    - name: Reload audit rules
      command: augenrules --load
      ignore_errors: true

    - name: Verify audit rule for sudo log file is applied
      command: "auditctl -l | grep -E '^ *-w.*{{ sudo_log_file_escaped }}.*-p.*wa'"
      register: audit_rule_check
      changed_when: false
      failed_when: false

    - name: Fail if the audit rule for sudo log file is not applied
      fail:
        msg: "Audit rule for sudo log file is not properly applied"
      when: audit_rule_check.stdout == ""

  handlers:
    - name: Reload sudoers
      command: visudo -c

    - name: Re-enable immutable mode
      command: auditctl -e 1
      when: audit_immutable == 1

    - name: Revert SELinux to enforcing
      command: setenforce 1
      when: selinux_status.stdout == "Enforcing"
