---
- name: Ensure events that modify the sudo log file are collected
  hosts: all
  become: true  # Ensure we run tasks as root

  tasks:
    # Ensure sudoers file has the logfile directive
    - name: Ensure the logfile directive is set in sudoers
      lineinfile:
        path: /etc/sudoers
        regexp: '^Defaults\s+logfile='
        line: 'Defaults logfile="/var/log/sudo.log"'
        validate: '/usr/sbin/visudo -cf %s'
      notify:
        - Reload sudoers

    # Extract sudo log file path from sudoers and escape for audit rule
    - name: Set sudo_log_file variable
      set_fact:
        sudo_log_file: "{{ lookup('pipe', 'grep -r logfile /etc/sudoers* | sed -e \"s/.*logfile=//;s/,? .*//\" -e \"s/\\\"\\\"//g\"') }}"

    - name: Escape sudo log file path for audit rule
      set_fact:
        sudo_log_file_escaped: "{{ sudo_log_file | regex_replace('/', '\\\\/') }}"

    # Check if audit system is in immutable mode and disable it temporarily
    - name: Check if audit system is in immutable mode
      command: auditctl -s
      register: audit_status
      changed_when: false

    - name: Disable immutable mode if necessary
      command: auditctl -e 0
      when: "'immutable' in audit_status.stdout"
      notify:
        - Re-enable immutable mode
      become: true  # Ensure the task is run as root

    # Ensure audit rule for sudo log file is present
    - name: Add audit rule for sudo log file if not present
      lineinfile:
        path: /etc/audit/rules.d/50-sudo.rules
        line: "-w {{ sudo_log_file }} -p wa -k sudo_log_file"
        create: yes
        state: present
      when: sudo_log_file != ""

    # Reload and apply audit rules using auditctl directly
    - name: Apply audit rule using auditctl directly
      command: "auditctl -w {{ sudo_log_file }} -p wa -k sudo_log_file"
      ignore_errors: yes
      become: true  # Ensure the task is run as root

    # Check if the audit rule has been applied
    - name: Verify audit rule for sudo log file is applied
      command: "auditctl -l | grep -E \"^ *-w.*{{ sudo_log_file_escaped }}.*-p.*wa\""
      register: audit_rule_check
      failed_when: false

    - name: Fail if the audit rule for sudo log file is not applied
      fail:
        msg: "Audit rule for sudo log file is not properly applied"
      when: audit_rule_check.stdout == ""

    - name: Success message
      debug:
        msg: "Audit rule for sudo log file is successfully applied"

  handlers:
    - name: Reload sudoers
      command: "visudo -c"
    
    - name: Re-enable immutable mode
      command: auditctl -e 1
      when: "'immutable' in audit_status.stdout"
      become: true  # Ensure the task is run as root
