---
- name: Ensure events that modify the sudo log file are collected
  hosts: all
  become: true

  tasks:

    # Check if the sudoers configuration contains the logfile setting
    - name: Check if sudoers file has the logfile directive
      command: "grep -r logfile /etc/sudoers*"
      register: sudo_logfile_check
      failed_when: false

    - name: Add logfile directive if missing in sudoers
      lineinfile:
        path: /etc/sudoers
        regexp: '^Defaults\s+logfile='
        line: 'Defaults logfile="/var/log/sudo.log"'
        validate: '/usr/sbin/visudo -cf %s'
      when: sudo_logfile_check.stdout == ""

    - name: Ensure the logfile directive is set in sudoers
      debug:
        msg: "The sudo log file is configured at: {{ sudo_logfile_check.stdout }}"
      when: sudo_logfile_check.stdout != ""

    # Extract the logfile path from sudoers file and escape it for use in the audit rule
    - name: Set SUDO_LOG_FILE variable
      set_fact:
        sudo_log_file: "{{ lookup('pipe', 'grep -r logfile /etc/sudoers* | sed -e \"s/.*logfile=//;s/,? .*//\" -e \"s/\\\"\\\"//g\"') }}"

    - name: Escape sudo log file path for audit rule
      set_fact:
        sudo_log_file_escaped: "{{ sudo_log_file | regex_replace('/', '\\\\/') }}"

    # Ensure audit rule for sudo log file is present
    - name: Add audit rule for sudo log file if not present
      lineinfile:
        path: /etc/audit/rules.d/50-sudo.rules
        line: "-w {{ sudo_log_file }} -p wa -k sudo_log_file"
        create: yes
        state: present
      when: sudo_log_file != ""

    # Merge and load audit rules
    - name: Merge and load the audit rules
      command: augenrules --load
      ignore_errors: yes

    - name: Check if reboot is required to load the rules
      command: "auditctl -s | grep 'enabled' | grep -q '2'"
      register: auditctl_check
      failed_when: false

    - name: Inform if reboot is required to load rules
      debug:
        msg: "Reboot required to load audit rules"
      when: auditctl_check.rc == 0

    # Verify the audit rule is active
    - name: Verify audit rule for sudo log file is applied
      command: "auditctl -l | grep -E '^ *-w.*{{ sudo_log_file_escaped }}.*-p.*wa'"
      register: audit_rule_check
      failed_when: false

    - name: Fail if the audit rule for sudo log file is not applied
      fail:
        msg: "Audit rule for sudo log file is not properly applied"
      when: audit_rule_check.stdout == ""

    - name: Success message
      debug:
        msg: "Audit rule for sudo log file is successfully applied"
