---
- name: Configure and load session initiation audit rules
  hosts: all
  become: true

  tasks:

    - name: Ensure /etc/audit/rules.d directory exists
      file:
        path: /etc/audit/rules.d
        state: directory
        mode: '0755'

    - name: Create or update session audit rules
      blockinfile:
        path: /etc/audit/rules.d/50-session.rules
        create: yes
        mode: '0644'
        block: |
          -w /var/run/utmp -p wa -k session
          -w /var/log/wtmp -p wa -k session
          -w /var/log/btmp -p wa -k session

    - name: Load the new audit rules with augenrules (ignore duplicate rule errors)
      command: augenrules --load
      register: augenrules_result
      failed_when: >
        augenrules_result.rc != 0 and
        'Rule exists' not in augenrules_result.stderr

    - name: Check if auditd is in immutable mode
      command: auditctl -s
      register: auditctl_status
      changed_when: false
      failed_when: false

    - name: Warn if auditd is in immutable mode
      debug:
        msg: "⚠️ Auditd is in immutable mode. Reboot is required to apply new rules."
      when: "'enabled = 2' in auditctl_status.stdout"

    - name: Ensure auditd service is running and enabled
      service:
        name: auditd
        state: started
        enabled: true
