---
- name: Harden system partitions and remediate mount options
  hosts: all
  become: true
  tasks:

    # Ensure nodev, nosuid, noexec options are set on /tmp partition
    - name: Ensure nodev, nosuid, noexec options are set on /tmp partition
      mount:
        name: /tmp
        fstype: "{{ ansible_mounts | selectattr('mount', 'equalto', '/tmp') | map(attribute='fstype') | first }}"
        opts: "defaults,rw,nosuid,nodev,noexec,relatime"
        state: mounted
      when: ansible_mounts | selectattr('mount', 'equalto', '/tmp') | length > 0

    # Ensure nodev, nosuid, noexec options are set on /home partition
    - name: Ensure nodev, nosuid, noexec options are set on /home partition
      mount:
        name: /home
        fstype: "{{ ansible_mounts | selectattr('mount', 'equalto', '/home') | map(attribute='fstype') | first }}"
        opts: "defaults,rw,nosuid,nodev,noexec,relatime"
        state: mounted
      when: ansible_mounts | selectattr('mount', 'equalto', '/home') | length > 0

    # Ensure noexec option on /var/tmp partition
    - name: Ensure noexec option on /var/tmp partition
      mount:
        path: /var/tmp
        fstype: xfs  # Adjust the fstype if necessary
        opts: "defaults,rw,nosuid,nodev,noexec,relatime"
        state: mounted
        passno: 0
        src: /dev/mapper/ocivolume-varTmp  # Adjust according to your partition device
      when: ansible_mounts | selectattr('mount', 'equalto', '/var/tmp') | list | length > 0

    # Ensure nodev option on /var/log partition
    - name: Ensure nodev option on /var/log partition
      mount:
        path: /var/log
        fstype: xfs  # Adjust the fstype if necessary
        opts: "defaults,rw,nosuid,nodev,noexec,relatime"
        state: mounted
        passno: 0
        src: /dev/mapper/ocivolume-varLog  # Adjust according to your partition device
      when: ansible_mounts | selectattr('mount', 'equalto', '/var/log') | list | length > 0

    # Ensure nosuid option on /var/log partition
    - name: Ensure nosuid option on /var/log partition
      mount:
        path: /var/log
        fstype: xfs  # Adjust the fstype if necessary
        opts: "defaults,rw,nosuid,nodev,noexec,relatime"
        state: mounted
        passno: 0
        src: /dev/mapper/ocivolume-varLog  # Adjust according to your partition device
      when: ansible_mounts | selectattr('mount', 'equalto', '/var/log') | list | length > 0

    # Ensure noexec option on /var/log partition
    - name: Ensure noexec option on /var/log partition
      mount:
        path: /var/log
        fstype: xfs  # Adjust the fstype if necessary
        opts: "defaults,rw,nosuid,nodev,noexec,relatime"
        state: mounted
        passno: 0
        src: /dev/mapper/ocivolume-varLog  # Adjust according to your partition device
      when: ansible_mounts | selectattr('mount', 'equalto', '/var/log') | list | length > 0

    # Ensure nodev option on /var/log/audit partition
    - name: Ensure nodev option on /var/log/audit partition
      mount:
        path: /var/log/audit
        fstype: xfs  # Adjust the fstype if necessary
        opts: "defaults,rw,nosuid,nodev,noexec,relatime"
        state: mounted
        passno: 0
        src: /dev/mapper/ocivolume-varLogAudit  # Adjust according to your partition device
      when: ansible_mounts | selectattr('mount', 'equalto', '/var/log/audit') | list | length > 0

    # Remount /tmp partition with the correct options
    - name: Remount /tmp partition with the correct options
      command: mount -o remount /tmp
      when: ansible_mounts | selectattr('mount', 'equalto', '/tmp') | length > 0

    # Remount /home partition with the correct options
    - name: Remount /home partition with the correct options
      command: mount -o remount /home
      when: ansible_mounts | selectattr('mount', 'equalto', '/home') | length > 0

    # Remount /var/tmp with updated options
    - name: Remount /var/tmp with updated options
      command: mount -o remount /var/tmp
      when: ansible_mounts | selectattr('mount', 'equalto', '/var/tmp') | list | length > 0

    # Remount /var/log with updated options
    - name: Remount /var/log with updated options
      command: mount -o remount /var/log
      when: ansible_mounts | selectattr('mount', 'equalto', '/var/log') | list | length > 0

    # Remount /var/log/audit with updated options
    - name: Remount /var/log/audit with updated options
      command: mount -o remount /var/log/audit
      when: ansible_mounts | selectattr('mount', 'equalto', '/var/log/audit') | list | length > 0

    # Ensure /etc/fstab has correct options for /tmp partition
    - name: Ensure /etc/fstab has correct options for /tmp partition
      lineinfile:
        path: /etc/fstab
        regexp: '^([^#]*\s+/tmp\s+[^#]+)'
        line: '\1,nosuid,nodev,noexec'
        create: yes

    # Ensure /etc/fstab has correct options for /home partition
    - name: Ensure /etc/fstab has correct options for /home partition
      lineinfile:
        path: /etc/fstab
        regexp: '^([^#]*\s+/home\s+[^#]+)'
        line: '\1,nosuid,nodev,noexec'
        create: yes

    # Ensure /etc/fstab has correct options for /var/tmp partition
    - name: Ensure /etc/fstab has correct options for /var/tmp partition
      lineinfile:
        path: /etc/fstab
        regexp: '^([^#]*\s+/var/tmp\s+[^#]+)'
        line: '\1,nosuid,nodev,noexec'
        create: yes

    # Ensure /etc/fstab has correct options for /var/log partition
    - name: Ensure /etc/fstab has correct options for /var/log partition
      lineinfile:
        path: /etc/fstab
        regexp: '^([^#]*\s+/var/log\s+[^#]+)'
        line: '\1,nosuid,nodev,noexec'
        create: yes

    # Ensure /etc/fstab has correct options for /var/log/audit partition
    - name: Ensure /etc/fstab has correct options for /var/log/audit partition
      lineinfile:
        path: /etc/fstab
        regexp: '^([^#]*\s+/var/log/audit\s+[^#]+)'
        line: '\1,nosuid,nodev,noexec'
        create: yes
